apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-docker-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-docker-app
  template:
    metadata:
      labels:
        app: go-docker-app
    spec:
      containers:
      - name: go-docker-app
        image: go-docker-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
